/* ============================================================
 *
 * This file is a part of digiKam project
 * https://www.digikam.org
 *
 * Date        : 2025-05-17
 * Description : a G'MIC Generic plugin dialog
 *
 * SPDX-FileCopyrightText: 2025 by Gilles Caulier <caulier dot gilles at gmail dot com>
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 *
 * ============================================================ */

#include "gmicqtgenericdlg.h"

// Qt includes

#include <QPushButton>
#include <QLabel>
#include <QComboBox>
#include <QLineEdit>
#include <QGridLayout>
#include <QDialogButtonBox>

// digiKam includes

#include "digikam_debug.h"
#include "ditemslist.h"
#include "dimg.h"

// Local includes

#include "gmicqtcommon.h"
#include "gmicqtprocessorthread.h"

namespace DigikamGenericGmicQtPlugin
{

class Q_DECL_HIDDEN GmicQtGenericDlg::Private
{
public:

    Private() = default;

public:

    QDialogButtonBox* buttons              = nullptr;
    DItemsList*       imageList            = nullptr;
    QWidget*          uploadWidget         = nullptr;
    QLineEdit*        fileTemplateLineEdit = nullptr;
    QComboBox*        imageFormat          = nullptr;
};

GmicQtGenericDlg::GmicQtGenericDlg(DPlugin* const tool, DInfoInterface* const iface, QWidget* const parent)
    : QDialog(parent),
      d      (new Private)
{
    setWindowTitle(tr("G'MIC-Qt (layers)"));

    d->buttons = new QDialogButtonBox(QDialogButtonBox::Help | QDialogButtonBox::Ok | QDialogButtonBox::Cancel, this);
    s_gmicQtPluginPopulateHelpButton(this, tool, d->buttons->button(QDialogButtonBox::Help));

    QWidget* const page     = new QWidget(this);
    QGridLayout* const grid = new QGridLayout(page);

    // --------------------------------------------------------

    QLabel* const inHeader  = new QLabel(page);
    inHeader->setWordWrap(true);
    inHeader->setText(tr("Set the list below with all stacked items to process by the G'MIC filter as layers."));

    d->imageList            = new DItemsList(page);
    d->imageList->setObjectName(QLatin1String("GmicGeneric ImagesList"));
    d->imageList->setControlButtonsPlacement(DItemsList::ControlButtonsRight);
    d->imageList->setIface(iface);
    d->imageList->listView()->clear();
    d->imageList->loadImagesFromCurrentSelection();

    // --------------------------------------------------------

    QLabel* const outHeader        = new QLabel(page);
    outHeader->setWordWrap(true);
    outHeader->setText(tr("Configure the G'MIC filter settings below to store the output images."));

    d->uploadWidget                = iface->uploadWidget(page);
    d->uploadWidget->setToolTip(tr("Select here the album where will be saved the output images generated by the G'MIC filter."));

    QLabel* const templateLbl      = new QLabel(tr("File Name Template:"), page);
    templateLbl->setWordWrap(false);

    d->fileTemplateLineEdit        = new QLineEdit(QLatin1String("gmic_output"), page);
    templateLbl->setBuddy(d->fileTemplateLineEdit);
    d->fileTemplateLineEdit->setToolTip(tr("Name of the G'MIC filter output files (without its extension)."));
    d->fileTemplateLineEdit->setWhatsThis(tr("\"File Name Template\": Set here the base name of the files that "
                                             "will be saved by the G'MIC filter. For example, if your template "
                                             "is \"gmic_output\" and if you chose a JPEG format, then the generated "
                                             "files will be saved with the name \"gmic_output_01.jpg\", "
                                             "\"gmic_output_02.jpg\", etc."));

    QLabel* const labelImageFormat = new QLabel(page);
    labelImageFormat->setWordWrap(false);
    labelImageFormat->setText(tr("Image Format:"));

    d->imageFormat                 = new QComboBox(page);
    d->imageFormat->setEditable(false);
    d->imageFormat->setToolTip(tr("Select your preferred G'MIC filter output image format."));
    d->imageFormat->addItem(QLatin1String("JPEG"), DImg::JPEG);
    d->imageFormat->addItem(QLatin1String("PNG"),  DImg::PNG);
    d->imageFormat->addItem(QLatin1String("TIFF"), DImg::TIFF);
    labelImageFormat->setBuddy(d->imageFormat);

    // --------------------------------------------------------

    grid->addWidget(inHeader,                0, 0, 1, 3);
    grid->addWidget(d->imageList,            1, 0, 1, 3);
    grid->addWidget(outHeader,               2, 0, 1, 3);
    grid->addWidget(d->uploadWidget,         3, 0, 1, 3);
    grid->addWidget(templateLbl,             4, 0, 1, 1);
    grid->addWidget(d->fileTemplateLineEdit, 4, 1, 1, 2);
    grid->addWidget(labelImageFormat,        5, 0, 1, 1);
    grid->addWidget(d->imageFormat,          5, 2, 1, 1);
    grid->setColumnStretch(0, 10);
    grid->setRowStretch(1, 5);
    grid->setRowStretch(3, 5);
    grid->setContentsMargins(QMargins());
    grid->setSpacing(layoutSpacing());

    QVBoxLayout* const vbx = new QVBoxLayout(this);
    vbx->addWidget(page);
    vbx->addWidget(d->buttons);
    setLayout(vbx);

    adjustSize();

    // --------------------------------------------------------

    connect(d->buttons->button(QDialogButtonBox::Ok), SIGNAL(clicked()),
            this, SLOT(accept()));

    connect(d->buttons->button(QDialogButtonBox::Cancel), SIGNAL(clicked()),
            this, SLOT(reject()));
}

GmicQtGenericDlg::~GmicQtGenericDlg()
{
    delete d;
}

QList<QUrl> GmicQtGenericDlg::imageUrls() const
{
    return d->imageList->imageUrls();
}

QString GmicQtGenericDlg::outputTemplate() const
{
    return d->fileTemplateLineEdit->text();
}

int GmicQtGenericDlg::outputFormat() const
{
    return d->imageFormat->currentData().toInt();
}

} // namespace DigikamGenericGmicQtPlugin

#include "moc_gmicqtgenericdlg.cpp"
